name: moti
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sliding_up_panel: ^2.0.0+1
  get: any
  flutter_svg: ^1.1.3
  yandex_mapkit: ^3.0.3
  location: ^4.4.0
  mask_text_input_formatter: ^2.4.0
  geocoding: ^2.0.4
  http: ^0.13.5
  hive_flutter: ^1.1.0
  device_preview: ^1.1.0
  scrollable_positioned_list: ^0.3.4
  geolocator: ^9.0.2
  cached_network_image: ^3.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
